ticket-list:
  # The format for broadcasted tickets
  # %name = player's name and %message = player's message
  ticket-message-format: '[&9StaffTickets&f] &9%name&f: %message'
  # Set this to false if you want tickets to not be deleted.
  delete-on-leave: true

  # Append on words.
  #   trigger:
  #   - some
  #   - words
  trigger:
  - water
  - fire
  - lava
  - grief
  - mod
  - portal

  # Set this to true whether you want ticket information logged.
  log-ticket-information: false

reminder:
  # Set this to true to enable ticket reminders.
  enable: false
  # The title header for your scheduled ticket reminders.
  # %ticketQty = The amount of tickets available.
  title-header: '&9+-------- &f[&9Notice &f(%ticketQty)] &9 --------+'
  # Interval is set to 10min by default
  interval: 10