name: StaffTickets
main: main.java.net.bigbadcraft.stafftickets.TicketPlugin
version: 2.0
commands:
  helpop:
    description: Submits a ticket using the ticket system.
  ticket:
    description: Displays a list of commands.
    permission: staffticket.mod
    permission-message: You do not have <permission>
  mytickets:
    description: View your helpop tickets.
    permissino: staffticket.myticket
    permission-message: You do not have <permission>